using Scalar.AspNetCore;

namespace OrderAggregator.Api.OpenApi;

/// <summary>
/// Registration and endpoint mapping for the OpenAPI document and the two
/// interactive UIs (Scalar + Swagger UI). Keeps the whole OpenAPI concern
/// (document transformers, generation, UIs) co-located in the OpenApi folder.
/// </summary>
public static class OpenApiExtensions
{
    /// <summary>
    /// Registers OpenAPI generation and the document/operation transformers that
    /// shape the contract (API key scheme, culture parameter, request examples).
    /// </summary>
    public static IServiceCollection AddAppOpenApi(this IServiceCollection services)
    {
        services.AddOpenApi(options =>
        {
            options.AddDocumentTransformer<OrderAggregatorDocumentTransformer>();
            options.AddDocumentTransformer<ApiKeySecuritySchemeDocumentTransformer>();
            options.AddDocumentTransformer<CultureParameterDocumentTransformer>();
            options.AddOperationTransformer<OrdersRequestOperationTransformer>();
            options.AddSchemaTransformer<ProblemDetailsSchemaTransformer>();
        });

        return services;
    }

    /// <summary>
    /// Maps the OpenAPI document and the interactive UIs. <c>/openapi/v1.json</c>
    /// is generated by Microsoft.AspNetCore.OpenApi; Scalar and Swagger UI both
    /// consume that document — so the contract is the single source of truth and
    /// the UIs stay in sync automatically. The site root redirects to Swagger UI.
    /// </summary>
    public static WebApplication MapOpenApi(this WebApplication app)
    {
        OpenApiEndpointRouteBuilderExtensions.MapOpenApi(app).AllowAnonymous();

        app.MapScalarApiReference(options =>
        {
            options
                .WithTitle("Order Aggregator API")
                .WithTheme(ScalarTheme.BluePlanet)
                .WithDefaultHttpClient(ScalarTarget.CSharp, ScalarClient.HttpClient);
        }).AllowAnonymous();

        app.UseSwaggerUI(options =>
        {
            options.SwaggerEndpoint("/openapi/v1.json", "Order Aggregator API v1");
            options.RoutePrefix = "swagger";
            options.DocumentTitle = "Order Aggregator API – Swagger UI";
        });

        // redirect to the OpenAPI UI
        app.MapGet("/", () => Results.Redirect("/swagger")).ExcludeFromDescription().AllowAnonymous();

        return app;
    }
}
